[phases.setup]
nixPkgs = [
  "python310",
  "opencv",
  "libGL",
  "glib",
  "ffmpeg"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"  # Yes, you SHOULD keep this
